# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sandglass.proto for package 'sandglass'

require 'grpc'
require 'sandglass_pb'

module Sandglass
  module BrokerService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sandglass.BrokerService'

      rpc :CreateTopic, CreateTopicParams, TopicReply
      rpc :PublishMessagesStream, stream(Message), StoreLocallyReply
      rpc :GetTopic, GetTopicParams, GetTopicReply
      rpc :Publish, Message, DUIDReply
      rpc :FetchFrom, FetchFromRequest, stream(Message)
      rpc :FetchRange, FetchRangeRequest, stream(Message)
      rpc :StoreMessagesStream, stream(Message), StoreLocallyReply
      rpc :ConsumeFromGroup, ConsumeFromGroupRequest, stream(Message)
      rpc :Acknowledge, OffsetChangeRequest, OffsetChangeReply
      rpc :AcknowledgeMessages, MultiOffsetChangeRequest, OffsetChangeReply
      rpc :Commit, OffsetChangeRequest, OffsetChangeReply
    end

    Stub = Service.rpc_stub_class
  end
  module InternalService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sandglass.InternalService'

      rpc :StoreMessageLocally, Message, StoreLocallyReply
      rpc :GetByKey, GetRequest, Message
      rpc :HasKey, GetRequest, HasResponse
      rpc :FetchFromSync, FetchFromSyncRequest, stream(Message)
      rpc :LastOffset, LastOffsetRequest, LastOffsetReply
      rpc :MarkConsumed, OffsetChangeRequest, OffsetChangeReply
      rpc :GetMarkStateMessage, OffsetChangeRequest, Message
    end

    Stub = Service.rpc_stub_class
  end
end
